name: 安卓解包

on:
#  schedule:
#    - cron: 5 6 * * 0
 workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: 环境设置
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff -a
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install unzip simg2img brotli
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
        sudo mkdir -p /workdir && ls
        sudo chown $USER:$GROUPS /workdir
        ln -sf /workdir $GITHUB_WORKSPACE/ROM
        df -h && ls -lh

    - name: 下载rom
      working-directory: /workdir
      run: |
        wget -q https://newcontinuum.dl.sourceforge.net/project/crdroid/begonia/7.x/crDroidAndroid-11.0-20220905-begonia-v7.21.zip && ls -lh
        unzip *.zip && ls -lh
        brotli -d system.new.dat.br && ls -lh
        #sdat2img system.transfer.list system.new.dat system.img && ls -lh

    - name: 上传 bin
      uses: actions/upload-artifact@main
      with:
        name: begonia
        path: /workdir/install/
        

    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: begonia-crdroid-11
        allowUpdates: true
        prerelease: false
        tag: begonia
        commit: 23.05
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: /workdir/*.zip
